import type { RawMessage } from "@/adapters/gmail";
import index from "../../fixtures/scenarios/index.json";
import s01 from "../../fixtures/scenarios/scenario-01.json";
import s02 from "../../fixtures/scenarios/scenario-02.json";
import s03 from "../../fixtures/scenarios/scenario-03.json";
import s04 from "../../fixtures/scenarios/scenario-04.json";
import s05 from "../../fixtures/scenarios/scenario-05.json";
import s06 from "../../fixtures/scenarios/scenario-06.json";
import s07 from "../../fixtures/scenarios/scenario-07.json";
import s08 from "../../fixtures/scenarios/scenario-08.json";
import type { Branch, ChaosMode } from "./types";

// Scenarios are the research fixtures (fixtures/scenarios, generated by fixtures/_gen.py), in real API shapes.

type Address = { city: string | null; country: string | null; line1: string | null; line2: string | null; postal_code: string | null; state: string | null };

export interface ScenarioFixture {
  name: string;
  chaos_mode: ChaosMode;
  scenario_prompt: string;
  seed: {
    stripe: {
      customer: { email: string; name: string };
      charge: {
        amount: number;
        description: string;
        metadata?: Record<string, string>;
        shipping?: { name: string; carrier: string | null; tracking_number: string | null; address: Address } | null;
      };
      dispute: { id: string; amount: number; reason: string; status: string; evidence_details: { due_by: number; past_due: boolean; submission_count: number } };
      refunds: { data: { amount: number }[] };
      prior_disputes: { data: { id: string; amount: number; status: string; reason: string; created: number }[] };
    };
    salesforce: {
      contact: { FirstName: string; LastName: string; Email: string; Description: string | null } | null;
      cases: { records: { Subject: string; Description: string | null }[] } | null;
    };
    gmail: { threads: { id: string; messages: RawMessage[] }[] };
  };
  expected_decision: Branch;
  expected_actions: string[];
  forbidden_effects: string[];
  assertions: { system: string; check: string; expected: unknown }[];
}

export interface Scenario {
  key: string;
  title: string;
  expected: Branch;
  chaos: ChaosMode;
  amount: number;
  email: string;
  needsApproval: boolean;
  fixture: ScenarioFixture;
}

export const MERCHANT = index.merchant;
export const APPROVAL_THRESHOLD_CENTS = index.approval_threshold_cents;
/** Fixture Slack channel ids → our channel kinds (the twin assigns real ids at runtime). */
export const FIXTURE_CHANNELS: Record<string, "disputes" | "approvals" | "risk"> = Object.fromEntries(
  Object.entries(index.slack_channels).map(([kind, id]) => [id, kind as "disputes" | "approvals" | "risk"]),
);

const files = { "scenario-01": s01, "scenario-02": s02, "scenario-03": s03, "scenario-04": s04, "scenario-05": s05, "scenario-06": s06, "scenario-07": s07, "scenario-08": s08 } as unknown as Record<string, ScenarioFixture>;

const title = (name: string) => name.replaceAll("_", " ").replace(/^\w/, (ch) => ch.toUpperCase());

export const SCENARIOS: Scenario[] = Object.entries(files).map(([key, f]) => ({
  key,
  title: title(f.name),
  expected: f.expected_decision,
  chaos: f.chaos_mode,
  amount: f.seed.stripe.dispute.amount,
  email: f.seed.stripe.customer.email,
  needsApproval: f.expected_decision === "ACCEPT" && f.seed.stripe.dispute.amount > APPROVAL_THRESHOLD_CENTS,
  fixture: f,
}));

/** Accepts "scenario-07", "07", "7" or the fixture name. */
export const scenarioByKey = (k: string) =>
  SCENARIOS.find((s) => s.key === k || s.fixture.name === k || s.key === `scenario-${k.padStart(2, "0")}`);
